repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        types: [python]
        files: ^Problems/.*\.py$
    -   id: mixed-line-ending
        types: [python]
        files: ^Problems/.*\.py$ 